# 使用 Python 3.9 作為基底映像檔
FROM python:3.9

# 設定工作目錄
WORKDIR /app

# 複製專案檔案到容器中
COPY . /app

# 安裝必要的 Python 套件
RUN pip install -r requirements.txt

# 開放 Flask 預設的 HTTP Port 8080
EXPOSE 8080

# 啟動 Flask 應用
CMD ["python", "app.py"]
